### ISSUE TITLE
REST service to provide a list of Rasa stories

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#102]
AS AN Architect
I WANT a REST service to provide a list of Rasa stories
SO THAT this functionality wouldn't be duplicated

### Acceptance Criteria

- [ ] Use `/rasa/stories` endpoint
- [ ] Use [Rasa `stories.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/stories.yml) as a source

#### Examples

Input

```yaml

version: "3.0"
stories:
- story: andmekaitse_küsimused
  steps:
  - intent: andmekaitse_küsimused
  - action: utter_andmekaitse_küsimused

- story: Deactivate custom fallback form
  steps:
  - action: custom_fallback_form
  - slot_was_set:
    - asukoht: Tallinn
  - action: action_react_to_affirm_deny_in_custom_fallback_form
```

Output

```json
["andmekaitse_küsimused", "Deactivate custom fallback form"]
```
