### ISSUE TITLE
REST service to provide a list of Rasa rules

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#103]
AS AN Architect
I WANT a REST service to provide a list of Rasa rules
SO THAT this functionality wouldn't be duplicated

### Acceptance Criteria

- [ ] Use `/rasa/rules` endpoint
- [ ] Use [Rasa `rules.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml) as a source

#### Examples

Input

```yaml
version: "3.0"
rules:
- rule: common_tervitus
  steps:
  - intent: common_tervitus
  - action: utter_common_tervitus

- rule: common_hüvasti_jätmine
  steps:
  - intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine
```

Output

```json
["common_tervitus", "common_hüvasti_jätmine"]
```
