### ISSUE TITLE
REST service to delete an existing Rasa rule

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#104]
AS AN Architect
I WANT to have a REST service to delete an existing Rasa rule
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto](http://proto.we.ee/burokratt/treening/treening/kasutuslood)

- [ ] Use POST endpoint `/rasa/rules/delete`
- [ ] Apply changes on [Rasa rules.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml)
- [ ] If #106 responds with `HTTP 200`, #108 is applied
- [ ] When deleting a rule, all of its sub-content gets deleted as well
- [ ] Changes apply only in case a rule with an input name provided (`rule_name`) already exists
> In relation to https://github.com/buerokratt/Training-Module/issues/85 <------ CORRECT THIS ONE

#### Example

Initial input

```yaml
forms:
  custom_fallback_form:
    required_slots:
        - affirm_deny
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```

Output after a request to delete `custom_fallback_form`

```yaml
forms:
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```
