### ISSUE TITLE
REST service to delete an existing Rasa story

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#109]
AS AN Architect
I WANT to have a REST service to delete an existing Rasa story
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto](http://proto.we.ee/burokratt/treening/treening/kasutuslood)

- [ ] Use POST endpoint `/rasa/stories/delete`
- [ ] Apply changes on [Rasa stories.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/stories.yml)
- [ ] If #106 responds with `HTTP 200`, #108 is applied
- [ ] When deleting a rule, all of its sub-content gets deleted as well
- [ ] Changes apply only in case a story with an input name provided (`story_name`) already exists
> In relation to https://github.com/buerokratt/Training-Module/issues/85 <------ CORRECT THIS ONE

#### Example

Initial input

```yaml
version: "3.0"
stories:
- story: andmekaitse_küsimused
  steps:
  - intent: andmekaitse_küsimused
  - action: utter_andmekaitse_küsimused
  
- story: Deactivate custom fallback form
  steps:
  - action: custom_fallback_form
  - slot_was_set:
    - asukoht: Tallinn
  - action: action_react_to_affirm_deny_in_custom_fallback_form
```

Output after a request to delete `andmekaitse_küsimused`

```yaml
version: "3.0"
stories:
- story: Deactivate custom fallback form
  steps:
  - action: custom_fallback_form
  - slot_was_set:
    - asukoht: Tallinn
  - action: action_react_to_affirm_deny_in_custom_fallback_form
```
