### ISSUE TITLE
REST service to create a new Rasa story

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#110]
AS AN Architect
I WANT to have a REST service to create new Rasa stories
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa stories](http://proto.we.ee/burokratt/treening/treening/kasutuslood/1)

- [x] Use POST endpoint `/rasa/stories/add` to create a new form
- [ ] Input provided as valid JSON, converted to YAML by #45
- [ ] Creating a new story is forbidden if #112 responds other than `HTTP 200`
- [ ] Apply changes on [Rasa stories.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/stories.yml)

### Examples

Input `stories.yml` before adding a new story

```yaml
version: "3.0"
stories:
- story: andmekaitse_küsimused
  steps:
  - intent: andmekaitse_küsimused
  - action: utter_andmekaitse_küsimused

- story: test
  steps:
  - intent: test
  - action: utter_test
  - checkpoint: check_stuff
```

Request to add a story `named` "tervitus" with `intents` "greeing_ee" and "greeing_en" and `action` "utter_laters", the resulting `stories.yml` would look like

```yml
version: "3.0"
stories:
- story: andmekaitse_küsimused
  steps:
  - intent: andmekaitse_küsimused
  - action: utter_andmekaitse_küsimused

- story: test
  steps:
  - intent: test
  - action: utter_test
  - checkpoint: check_stuff

- story: tervitus
  steps:
  - intent: greeing_ee
  - intent: greeing_en
  - action: utter_laters
```
