### ISSUE TITLE
REST service to create a new Rasa rule

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#111]
AS AN Architect
I WANT to have a REST service to create a new Rasa rule
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa stories](http://proto.we.ee/burokratt/treening/treening/kasutuslood/1)

- [ ] Use POST endpoint `/rasa/rules/add` to create a new rule
- [ ] Input provided as valid JSON, converted to YAML by #45
- [ ] Creating a new rule is forbidden if #113 responds other than `HTTP 200`
- [ ] Apply changes on [Rasa stories.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml)

> NB! Validate if not exists

### Examples

Input `rules.yml` before adding a new story

```yaml
version: "3.0"
rules:
- rule: common_tervitus
  steps:
  - intent: common_tervitus
  - action: utter_common_tervitus

- rule: common_hüvasti_jätmine
  steps:
  - intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine
```

Request to add a story `named` "tervitus" with `intents` "greeing_ee" and "greeing_en" and `action` "utter_laters", the resulting `rules.yml` would look like

```yml
version: "3.0"
rules:
- rule: common_tervitus
  steps:
  - intent: common_tervitus
  - action: utter_common_tervitus

- rule: common_hüvasti_jätmine
  steps:
  - intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine

- rule: tervitus
  steps:
  - intent: greeing_ee
  - intent: greeing_en
  - action: utter_laters
```
