### ISSUE TITLE
REST service to fetch content of a specific story

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#112]
AS AN Architect
I WANT to have a REST service to fetch content of a specific story
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/stories` with POST `story_name` parameter as input
- [ ] Use https://github.com/buerokratt/Training-Module/blob/main/mock1/data/stories.yml as a source of truth
- [ ] Response contains only the content of a specified story

#### Examples

`stories.yml`

```yaml
version: "3.0"
stories:
- story: andmekaitse_küsimused
  steps:
  - intent: andmekaitse_küsimused
  - action: utter_andmekaitse_küsimused
  
- story: Deactivate custom fallback form
  steps:
  - action: custom_fallback_form
  - slot_was_set:
    - asukoht: Tallinn
  - action: action_react_to_affirm_deny_in_custom_fallback_form

- story: test
  steps:
  - intent: test
  - action: utter_test
  - checkpoint: check_stuff
```

Output for a request for story `andmekaitse_küsimused`

```json
{
  "story": "andmekaitse_küsimused",
  "steps": [{
      "intent": "andmekaitse_küsimused"
    },
    {
      "action": "utter_andmekaitse_küsimused"
    }
  ]
}
```
