### ISSUE TITLE
REST service to fetch content of a specific rule

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#113]
AS AN Architect
I WANT to have a REST service to fetch the content of a specific rule
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/rules` with POST `rule_name` parameter as input
- [ ] Use https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml as a source of truth
- [ ] Response contains only the content of a specified story

#### Examples

`stories.yml`

```yaml
version: "3.0"
rules:
- rule: common_tervitus_conversation
  conversation_start: true
  steps:
  - intent: common_tervitus
  - action: utter_common_esimene_tervitus

- rule: common_tervitus
  steps:
  - intent: common_tervitus
  - action: utter_common_tervitus

- rule: common_hüvasti_jätmine
  steps:
  - intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine
```

Output for a request for story `common_tervitus`

```json
{
  "rule": "common_tervitus",
  "steps": [
    {
      "intent": "common_tervitus"
    },
    {
      "action": "utter_common_tervitus"
    }
  ]
}
```
