### ISSUE TITLE
REST service to delete an existing Rasa test story

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#119]
AS AN Architect
I WANT to have a REST service to delete an existing Rasa test story
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8

- [ ] Use POST endpoint `/rasa/test-stories/delete` to delete an existing response
- [ ] Deleting a test story expects #106 to respond with `HTTP 200`
- [ ] Apply changes on [Rasa tests/test_stories.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/tests/test_stories.yml)
- [ ] When deleting a response, all of its sub-content gets deleted as well

#### Example

Input `tests/test_stories.yml` before deleting a specified story

```yaml
stories:
- story: common_tervitus
  steps:
  - user: |
      tere
    intent: common_tervitus
  - action: utter_common_tervitus

- story: common_hüvasti_jätmine
  steps:
  - user: |
      headaega
    intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine
```

Output after a request to delete `common_tervitus`

```yaml
stories:
- story: common_hüvasti_jätmine
  steps:
  - user: |
      headaega
    intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine
```
