### ISSUE TITLE
REST service to provide full content of a specified Rasa regex

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#125]
AS AN Architect
I WANT TO have a REST service to fetch the full content of a specified Rasa regex
SO THAT there wouldn't be any duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/regex` with a POST parameter as an input
- [ ] Use `regex` section of [Rasa `data/regex_nlu.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/regex_nlu.yml#L3-L72) as input
- [ ] When using `examples=true` as an input POST parameter, the output provides full content, including examples
- [ ] When using `examples=false` as an input POST parameter, only a list of appropriate files with intent names is returned
- [ ] By default, `examples=false` is used

#### Examples

Sample input

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
```

Output for requesting "asukoht" as an input

##### `examples=false`

```json
true
```

##### `examples=true`

```json
{
  "asukoht": ["abja[- ]paluoja", "antsla", "elva", "haapsalu"]
}
```
