### ISSUE TITLE
REST service to update the content of a specified Rasa regex

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#128]
AS AN Architect
I WANT TO have a REST service to update an existing Rasa regex
SO THAT there wouldn't be any duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/regex/update` to add a new Rasa regex
- [ ] Apply changes on [Rasa `data/regex_nlu.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/regex_nlu.yml) as input
- [ ] Apply changes to a specified `entity`
- [ ] Apply changes to examples based on exact match -- @vmugra , please confirm

#### `data/regex_nlu.yml`

Input

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
 
- regex: nimed
  examples: |
    - büro
    - kratt
    - bürokratt
```

Output after making a request to update "antsla" to "[Aa]ntsla" within entity "asukoht"

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - [Aa]ntsla
    - elva
    - haapsalu
 
- regex: nimed
  examples: |
    - büro
    - kratt
    - bürokratt
```
