### ISSUE TITLE
REST service to delete a specified example in Rasa regex

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#129]
AS AN Architect
I WANT TO have a REST service to delete an existing Rasa regex
SO THAT there wouldn't be any duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/regex/delete-example` to delete an existing Rasa entity
- [ ] Only proceed if #130 with input `examples=false` responds with `HTTP 200`
- [ ] Apply changes on [Rasa `/data/regex_nlu.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/regex_nlu.yml) file of a specified entity
- [ ] Deleting the whole regex section for a specific topic is out of scope of this task
> Deletion will be solved by having a separate file for every example (not just 1 big file containing everything as is done right now), which will then be deleted as a whole, if chosen to

### Examples

Input `domain.yml`

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
```

Output after a request to delete `asukoht.elva `

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - haapsalu
```
