### ISSUE TITLE
REST service to add a new regex

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#325]
AS AN Architect
I WANT TO have a REST service to add a new Rasa `regex` example
SO THAT there wouldn't be any duplicate services for it

### Acceptance Criteria

- [x] Use POST endpoint `/rasa/regexes/add` to add a new Rasa `regex` example
- [ ] Create a separate `regex/[name]_nlu.yml` for every `regex`, where `[name]` represents the name of the nlu

### Examples

Sample input of `/data/regex/asukoht_nlu.yml`

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
```
Sample input of `/data/regex/aastaaeg_nlu.yml`

```yaml
version: "3.0"
nlu:
- regex: aastaaeg
  examples: |
    - kevad
    - suvi
    - sügis
    - talv
```
