### ISSUE TITLE
REST service to add example to a new regex

### ISSUE THREAD

**Issue by Kristjan259** [buerokratt/Training-Module#334]
AS AN Architect
I WANT TO have a REST service to add new examples into regexes
SO THAT there wouldn't be any duplicate services for it

## Acceptance Criteria

- [x] Use POST endpoint `/rasa/regexes/add-example` to add a new Rasa example to a given`regex`

## Examples

Sample input to `/data/regex/asukoht_nlu.yml`

Example of request body:

```json
{ 
    "regex": "asukoht", 
    "example": "tartu"
}
```

The `/data/regex/asukoht_nlu.yml` before adding:

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
```

The `/data/regex/asukoht_nlu.yml` after adding:

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
    - tartu
```
