### ISSUE TITLE
REST service to update the name of a specified Rasa regex 

### ISSUE THREAD

**Issue by Kristjan259** [buerokratt/Training-Module#339]
AS AN Architect
I WANT TO have a REST service to update an existing Rasa regex
SO THAT there wouldn't be any duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/regex/update` to update the name of the Rasa regex nlu file

#### `data/asukoht_nlu.yml`
Input

```yaml
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
 
```

Output after making a request to update regex name"asukoht" to "asukohad" and the name of the file is updated from "asukoht.yml" to "asukohad.yml"

```yaml
version: "3.0"
nlu:
- regex: asukohad
  examples: |
    - abja[- ]paluoja
    - antsla
    - elva
    - haapsalu
 
```
