### ISSUE TITLE
GUI for Synonyms

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#54]
### Acceptance Criterias:

- [ ] Display `list of Synonyms`
- [ ] Select Synonym from list
- [ ] Modify Synonym value (i.e. Tallinn)
- [ ] Select `intent` for each Synonym - ????
- [ ] `Go to intent` button - ?????
- [ ] Add new Synonym examples
- [ ] Search Synonym examples
- [ ] Delete Synonym (+ ask confirmation before deleted)
- [ ] Display introduction text/link to kratid.ee for how to make a Synonyms

> See Synonyms documentation: https://rasa.com/docs/rasa/nlu-training-data#synonyms

`Synonyms` map extracted entities to a value other than the literal text extracted. You can use Synonyms when there are `multiple ways users refer to the same thing`. Synonyms mapping only happens `after entities have been extracted`. That means that your `training examples should include the Synonyms examples` (credit card account and credit account) so that the model will learn to recognize these as entities and replace them with credit.

![image](https://user-images.githubusercontent.com/46499312/212890546-0c926acb-73be-4237-abac-73631c608255.png)

EXAMPLE:
```
version: "3.0"
nlu:
- regex: asukoht
  examples: |
    - [Tt]allinn
    - [Tt]amsalu
    - [Tt]apa
   
- synonym: tallinn
  examples: |
    - pealinn
    - suurlinn
    - suurlinnas

- intent: rahvaarv
  examples: |
    - palju rahvast eestis elab
    - kui palju elanikke meil on
    - mitu inimest harjumaal on
    - inimeste arv
    - rahvaarv
    - eesti rahvastik
    - mitu inimest [tallinn](asukoht) elab
    - rahvaarv [pealinnas](asukoht)
```

> different option:  # - rahvaarv [pealinnas]{"entity": "asukoht", "value": "tallinn"}
