### ISSUE TITLE
GUI for writing rules and stories - rule/story specific requirements

### ISSUE THREAD

**Issue by vmugra** [buerokratt/Training-Module#71]
### General acceptance criterias:
- [x] Lists of **intents/Teemad**, **responses/Vastused**, **form/Vormid**, **special actions/Reeglitäiendid** and **conditions/Tingimused**! (left column)
- [x] Add or edit name (NB! Name field can not be empty)
- [x] New rule/story can not be added without a naming a rule/story
- [x] Start Again, Cancel, Save buttons

### **Intents**:
- [x] D&D display as: `Teema: common_kuidas_läheb`
- [x] Add entity for intent (+ add entity) after intent is added as a story/rule step-> can add multiple entities for one intent and delete them
![image](https://user-images.githubusercontent.com/46499312/212927065-1413e5cf-30ad-45c9-82e9-7307ecfb6982.png)
- [x] Choose entity from list of entities related to the specific intent
Example: ![image](https://user-images.githubusercontent.com/46499312/213113206-14e08326-ce68-491c-b0c8-da9929e6d269.png)

### **Responses:**
- [x] Choose from list of responses (from domain.yml file)
- [x] D&D display as: `Vastus: utter_common_kuidas_läheb`

### **Forms:**
- [ ] RulePolicy must be activated (Error message if not)
> https://rasa.com/docs/rasa/forms & https://rasa.com/docs/rasa/forms#writing-stories--rules-for-unhappy-form-paths & https://rasa.com/docs/rasa/stories#form-events

- [x] Add a form
> D&D display as `Vorm: eesnimi_form` (i.e. - action: restaurant_form in yaml files)
- [x] Add active_loop `**after form**`
> choose from form name or null as action description (i.e. `- active_loop: restaurant_form` or `- active_loop: null` in yaml files)
> active_loop can be either -> ` - active_loop: form name from list` <- this is for activating a form `- active_loop: null` <- this is for deactivating a form
<img width="661" alt="image" src="https://user-images.githubusercontent.com/46499312/214045031-f91e2203-7e82-4f79-a48b-8e80a960c81c.png">

![image](https://user-images.githubusercontent.com/46499312/213111684-90508030-d135-4626-aaf8-82a094e29490.png)

Form in a rule EXAMPLE:
```
rules:
- rule: Example of an unhappy path
  condition: <- usage of conditions
  # Condition that form is active.
  **- active_loop: restaurant_form** <- usage of active_loop
  steps:
  - intent: chitchat
  - action: utter_chitchat
  - action: restaurant_form <- usage of forms
  - active_loop: restaurant_form <- usage of active_loop with forms!
```

Form in a story EXAMPLE
```
stories:
- story: User interrupts the form and doesn't want to continue
  steps:
  - intent: request_restaurant
  - action: restaurant_form <- usage of forms
  - active_loop: restaurant_form  <- usage of active_loop
  - intent: stop
  - action: utter_ask_continue <- usage of utter ask (with forms)
  - intent: stop
  - action: action_deactivate_loop <- usage of action_deactivate_loop
  - active_loop: null <- usage of active_loop with null status
```

### Slot events

- [ ]`Slot_was_set` and choose slots and their values (text field or null)
![image](https://user-images.githubusercontent.com/46499312/213113969-b3decad2-7f65-4a4b-bfb8-779581ee902b.png)

<img width="452" alt="image" src="https://user-images.githubusercontent.com/46499312/214239926-54cb0cf8-f515-4a7a-92b9-362251faf08f.png">

examples:
```
stories:
- story: set slot to none
  steps:
    # ... other story steps
    - action: my_custom_action
    - slot_was_set:
      - my_slot: null
```
https://rasa.com/docs/rasa/stories#slot-events

> Slot events are written under slot_was_set in a story. If this slot is set inside a custom action, add the slot_was_set event immediately following the custom action call. If your custom action resets a slot value to None, the corresponding event for that would look like this:

stories:

### **Deleting a step:**
- [x] Activate a step and delete everything after the step (see below)
![image](https://user-images.githubusercontent.com/46499312/212920486-623a3100-4831-40e4-91ab-52bb5fe9cf4a.png)
- [x] Start again button (displayed next to "Tagasi")
- [x] Ask confirmation to delete or start again

### Conditions: - Applies only for rules!
 _(NB! This will be checked if conditions can be in stories as well)_
> At the START of the conversation there is a conditions section where multiplee conditions can be set. Examples: https://rasa.com/docs/rasa/rules#rules-with-conditions
![image](https://user-images.githubusercontent.com/46499312/212917085-9521f139-276c-45d6-b63c-979b2c16c13f.png)

- [x] Choose condition `slot_was_set: slot name` 
- [x] Choose condition `active_loop: form name`

<img width="661" alt="image" src="https://user-images.githubusercontent.com/46499312/214047597-9e9f4f4a-1c64-4933-9ca8-9af9b3daf8ab.png">

### **Special actions:**
- [ ] D&D display as: `Tegevus: xxx`
- [ ] `active_loop: null`

**Special action requirements applicable only for rules:**
> Rules are great to handle small specific conversation patterns, but unlike [stories](https://rasa.com/docs/rasa/stories), rules don't have the power to generalize to unseen conversation paths. Rules can additionally contain the conversation_started and conditions keys. See more: https://rasa.com/docs/rasa/rules/#writing-a-rule
- [ ] Rule Policy must be activated before creating a new rule (Send notification if not active) 
1. `conversation_start: true` 
> Always as a FIRST step of the rule. This can only be as a first step of the rule! Indicates for start of the conversation. 
![image](https://user-images.githubusercontent.com/46499312/212902098-aab7fc32-cecc-48ea-963d-26e75ba33bbb.png)
2. `action_listen` and `action_restart`
> Any step of the rule
3.  `wait_for_user_input: false`
> Always as a LAST step of the rule. If you want to hand over the next action prediction to another story or rule, add wait_for_user_input: false to your rule.

**Special action requirements applicable only for Stories:**
1. `checkpoints` - special acion for stories only
Display as:
`- checkpoint: "value in text"`
![image](https://user-images.githubusercontent.com/46499312/213114587-a7f26216-10fd-4c4f-abb6-0c7f234b5bb9.png)

<img width="386" alt="image" src="https://user-images.githubusercontent.com/46499312/214350430-842d16a9-a964-4655-973f-12bfa664a93b.png"> <img width="386" alt="image" src="https://user-images.githubusercontent.com/46499312/214350563-9d66016b-574c-420e-ac0b-3ee72d4877e6.png">
