### ISSUE TITLE
[BUG] Slot rules in Training Module not functioning as intended

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#771]
**Bug description:**
When creating/modifying a rule that checks slots using `slot_was_set`, the Rasa rules syntax is broken due to a missing hyphen (-) before the slot name. This is an example of a broken rule:
```
  - rule: common_teenus_rk_hääletus_viimased
    steps:
      - slot_was_set:
          rk_hääletused: true
      - intent: common_teenus_rk_hääletus
      - action: utter_common_teenus_rk_hääletus_viimased
      - action: action_restart
```

**Expected behavior:**
This is how the rule should be:
```
  - rule: common_teenus_rk_hääletus_viimased
    steps:
      - slot_was_set:
          - rk_hääletused: true
      - intent: common_teenus_rk_hääletus
      - action: utter_common_teenus_rk_hääletus_viimased
      - action: action_restart
```

**Screenshots:**

**Additional information:**
When looking at the http response, a rule that is not broken has the slot name and value in an array (`{slot_was_set: [{rk_hääletused: true}]}`), while for a broken rule that is not the case (`{slot_was_set: {rk_hääletused: true}}`)
