### ISSUE TITLE
Deleting intents in Training Module

### ISSUE THREAD

**Issue by jaX10bt** [buerokratt/Training-Module#780]
**AS A** *chatbot trainer*
**I WANT** *to be able to fully delete intents using the GUI*
**SO THAT** *I can delete redundant or unnecessary intents without issues*

Currently /rasa/intents/delete.yml tries to move the deleted intent to a directory named '/removed'.
```
saveIntentFile:
  call: http.post
  args:
    url: "[#TRAINING_DMAPPER]/file-manager/create"
    body:
      file_path: ${fileLocations.response.body.response.intents_location + "removed/" + intent + file_end}
      content: ${intentYaml.response.body.json}
  result: fileResult
```
If this directory is missing, the intent deletion fails. If the directory exists, the intent is moved there, but is not fully deleted. The deleted intents are still visible as *empty* intent options in the GUI under rule creation.
![Image](https://github.com/user-attachments/assets/d022c1fd-b7c5-4e41-84a7-940e2ed058a7)

### Acceptance Criteria

- [x] When a user clicks "delete intent" in the GUI, the intent file is fully deleted from the /nlu directory
- [ ] ~When a user clicks "delete intent" in the GUI, all relevant data is removed from the domain.yml file~
- [ ] ~When a user clicks "delete intent" in the GUI, rules regarding the intent are removed from the rules.yml file~
