### ISSUE TITLE
Deleting intents with rule and story dependencies

### ISSUE THREAD

**Issue by IgorKrupenja** [buerokratt/Training-Module#787]
**AS A** _chatbot trainer_ 
**I WANT** _to be able to fully delete intents with  using the GUI_ 
**SO THAT** _I can delete redundant or unnecessary intents without issues_

1. Open https://admin.test.buerokratt.ee/training/training/intents.
2. Select an intent with rule or story dependency, e.g. "common service companies employees".
3. Click Delete (Kustuta).

Deleting the intent will fail due to this step in `/rasa/intents/delete.yml`:

```yaml
validateRuleDependency:
  switch:
    - condition: ${rulesYaml.response.body.json.includes("intent:" + " " + parameters.name)}
      next: returnRuleDependency
  next: getStoriesFile
```

If there is a rule dependency, the intent will not be deleted. Same with story dependencies and `validateStoriesDependency`. This issue is a follow-up to https://github.com/buerokratt/Training-Module/issues/780 , agreed with @ffrose that he will double-check what are the correct expectations here.
 
### Acceptance Criteria

**NB! Not final, might need to be revised.**

 * [ ] Intents with rule or story dependencies can be deleted.
 * [ ]  When a user clicks "delete intent" in the GUI, all relevant data is removed from the domain.yml file
 * [ ]  When a user clicks "delete intent" in the GUI, rules regarding the intent are removed from the rules.yml file
 * [ ]  When a user clicks "delete intent" in the GUI, rules regarding the intent are removed from the stories.yml file
