### ISSUE TITLE
Fetch a list of all Rasa slots

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#82]
AS AN Architect
I WANT to have a REST service to fetch all Rasa slots
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8

- [ ] Use GET endpoint `/rasa/slots` to list all slots
- [ ] Source of truth to fetch a list of Rasa slots is [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L17-L39)

#### Example of input and output

`slots` of `domain.yml` as a raw input

```yaml
slots:
  common_teenus_ilm_asukoht:
    type: text
    influence_conversation: true
    mappings:
    - type: from_entity
      entity: asukoht
      intent: common_teenus_ilm
    - type: from_entity
      entity: asukoht
      intent: nlu_fallback

  affirm_deny:
    type: text
    influence_conversation: true
    mappings:
    - type: from_text
      conditions:
      - active_loop: custom_fallback_form
        requested_slot: affirm_deny
      - active_loop: direct_to_customer_support_form
        requested_slot: affirm_deny
```

Output for `/rasa/slots`

```
["common_teenus_ilm_asukoht", "affirm_deny"]
```
