### ISSUE TITLE
REST service to fetch a list of all Rasa forms

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#83]
AS AN Architect
I WANT to have a REST service to fetch all Rasa forms
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8

- [x] Use GET endpoint `/rasa/forms` to list all forms
- [ ] Source of truth to fetch a list of Rasa forms is [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L41-L47)

#### Example of input and output

`forms` of `domain.yml` as a raw input

```yaml
forms:
  custom_fallback_form:
    required_slots:
        - affirm_deny
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```

Output for `/rasa/forms`

```
["custom_fallback_form", "direct_to_customer_support_form"]
```
