### ISSUE TITLE
REST service to create new Rasa forms

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#84]
AS AN Architect
I WANT to have a REST service to create new Rasa forms
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa forms](http://proto.we.ee/burokratt/treening/treening/vormid/uus)

- [x] Use POST endpoint `/rasa/forms/add` to create a new form
- [ ] ~All form names in `domain.yml` must end with `_form` - apply automatically, if not provided in the input~
- [x] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L41-L47)

#### Example output

```yaml
forms:
  restaurant_form:
    ignored_intents: 
    - chitchat
    required_slots:
        - cuisine
        - num_people
```

**Comment by vmugra** [comment]
https://rasa.com/docs/rasa/forms/#defining-a-form
```
entities:
- cuisine
- number
slots:
  cuisine:
    type: text
    mappings:
    - type: from_entity
      entity: cuisine
  num_people:
    type: any
    mappings:
    - type: from_entity
      entity: number
forms:
  restaurant_form:
    ignored_intents: 
    - chitchat
    required_slots:
        - cuisine
        - num_people
```
