### ISSUE TITLE
REST service to update an existing Rasa form

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#85]
AS AN Architect
I WANT to have a REST service to update an existing Rasa form
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa forms](http://proto.we.ee/burokratt/treening/treening/vormid/1)

- [ ] Use POST endpoint `/rasa/forms/update` to update an existing form
- [ ] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L41-L47)
- [ ] ~All form names in `domain.yml` must end with `_form` - apply automatically, if not provided in the input~
- [ ] Changes apply only in case a form with an input name provided (`form_name`) already exists
- [ ] In relation to https://github.com/buerokratt/Training-Module/issues/84

#### Example output

```yaml
forms:
  restaurant_form:
    ignored_intents: 
    - chitchat
    required_slots:
        - cuisine
        - num_people
```
