### ISSUE TITLE
REST service to delete an existing Rasa form

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#86]
AS AN Architect
I WANT to have a REST service to delete an existing Rasa form
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa forms](http://proto.we.ee/burokratt/treening/treening/vormid)

- [x] Use POST endpoint `/rasa/forms/delete` to delete an existing form
- [x] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L41-L47)
- [x] Deleting a form is forbidden if #96 responds with `HTTP 200` for a request to find a matching form
- [x] Deleting a form is forbidden if #97 responds with `HTTP 200` for a request to find a matching form
- [ ] When deleting a form, all of its sub-content gets deleted as well
- [ ] Changes apply only in case a form with an input name provided (`form_name`) already exists
- [ ] In relation to https://github.com/buerokratt/Training-Module/issues/85

#### Example

Initial input

```yaml
forms:
  custom_fallback_form:
    required_slots:
        - affirm_deny
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```

Output after a request to delete `custom_fallback_form`

```yaml
forms:
  direct_to_customer_support_form:
    required_slots:
        - affirm_deny
```
