### ISSUE TITLE
REST service to create new Rasa slots

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#87]
AS AN Architect
I WANT to have a REST service to create new Rasa slots
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa slots](http://proto.we.ee/burokratt/treening/treening/malukohad/uus)

> `slots.<slot name>.mappings.conditions` are out of scope

- [x] Use POST endpoint `/rasa/slots/add` to create a new form
- [x] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L17-L39)

### Examples

Initial source

```yaml
slots:
  common_teenus_ilm_asukoht:
    type: text
    influence_conversation: true
    mappings:
    - type: from_entity
      entity: asukoht
      intent: common_teenus_ilm
```

in which `slots.type: text` if always fixed as is.

#### Add more intents

When adding `nlu_fallback` and `rahvaarv` as additional intents, `slots.common_teenus_ilm_asukoht.mappings.type: from_entity` and `slots.common_teenus_ilm_asukoht.mappings.entity: asukoht` apply to all intents selected

```yaml
slots:
  common_teenus_ilm_asukoht:
    type: text
    influence_conversation: true
    mappings:
    - type: from_entity
      entity: asukoht
      intent: common_teenus_ilm
    - type: from_entity
      entity: asukoht
      intent: nlu_fallback
    - type: from_entity
      entity: asukoht
      intent: rahvaarv
```

**Comment by vmugra** [comment]
Examples of creating a new slot: https://rasa.com/docs/rasa/domain#slots

Add a slot with **mapping type `from_entity`**:
```
slots:
  slot_name:
    type: text
    mappings:
    - type: from_entity
      entity: entity_name
```
Add a slot with **type `entity`**:
