### ISSUE TITLE
REST service to update an existing Rasa slot

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#88]
AS AN Architect
I WANT to have a REST service to update an existing Rasa slot
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa forms](http://proto.we.ee/burokratt/treening/treening/malukohad/1)

- [ ] Use POST endpoint `/rasa/slots/update` to update an existing slot
- [ ] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L17-L39)
- [ ] When updating slots, use #87 to re-write an existing slot with new content
- [ ] Changes apply only in case a form with an input name provided (`form_name`) already exists

#### Example

Initial input

```yaml
slots:
  common_teenus_ilm_asukoht:
    type: text
    influence_conversation: true
    mappings:
    - type: from_entity
      entity: asukoht
      intent: common_teenus_ilm
    - type: from_entity
      entity: asukoht
      intent: nlu_fallback
    - type: from_entity
      entity: asukoht
      intent: rahvaarv
```

Output after a request to remove `nlu_fallback` and `rahvaarv`

```yaml
slots:
  common_teenus_ilm_asukoht:
    type: text
    influence_conversation: true
    mappings:
    - type: from_entity
      entity: asukoht
      intent: common_teenus_ilm
```
