### ISSUE TITLE
REST service to delete an existing Rasa slot

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#89]
AS AN Architect
I WANT to have a REST service to delete an existing Rasa slot
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

> Temporary list of endpoints - https://github.com/buerokratt/Buerokratt-onboarding/issues/8
> [Proto to add new Rasa forms](http://proto.we.ee/burokratt/treening/treening/malukohad)

- [ ] Use POST endpoint `/rasa/slots/delete` to delete an existing slots
- [ ] Apply changes on [Rasa domain.yml](https://github.com/buerokratt/Training-Module/blob/main/mock1/domain.yml#L17-L39)
- [ ] Changes apply only in case a slot with an input name provided (`slot_name`) already exists
- [ ] Deleting a slot is forbidden if #95 responds with `HTTP 200` for a request to find a matching slot
- [ ] Deleting a slot is forbidden if #96 responds with `HTTP 200` for a request to find a matching slot
- [ ] Deleting a slot is forbidden if #97 responds with `HTTP 200` for a request to find a matching slot
- [ ] When deleting a slot, all of its sub-content gets deleted as well
- [ ] In relation to https://github.com/buerokratt/Training-Module/issues/88

#### Example

Initial input

```yaml
slots:
  affirm_deny:
    type: text
    mappings:
    - type: from_text
      conditions:
      - active_loop: custom_fallback_form
        requested_slot: affirm_deny
      - active_loop: direct_to_customer_support_form
        requested_slot: affirm_deny
  common_teenus_ilm_asukoht:
    type: text
    influence_conversation: true
    mappings:
    - type: from_entity
      entity: asukoht
      intent: common_teenus_ilm
    - type: from_entity
      entity: asukoht
      intent: nlu_fallback
    - type: from_entity
      entity: asukoht
      intent: rahvaarv
```

Output after a request to delete `common_teenus_ilm_asukoht`

```yaml
slots:
  affirm_deny:
    type: text
    mappings:
    - type: from_text
      conditions:
      - active_loop: custom_fallback_form
        requested_slot: affirm_deny
      - active_loop: direct_to_customer_support_form
        requested_slot: affirm_deny
```
