### ISSUE TITLE
List all Rasa rules requiring specified slots, forms or responses

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Training-Module#96]
AS AN Architect
I WANT to have a REST service to list all Rasa rules requiring specified slots
SO THAT there wouldn't be duplicate services for it

### Acceptance Criteria

- [ ] Use POST endpoint `/rasa/rules/search` with input parameters `type: slots/forms` and `input: {JSON array}`
- [ ] [Rasa `rules.yml`](https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml) as source of truth
- [ ] Search within OpenSearch
> OpenSearch fed with input via a separate pipeline

#### Search for required slots

Slots are defined by defining `slot_was_set`, for example, `rules.rule.steps.slot_was_set`, `rules.rule.condition.slot_was_set`, etc.

```yaml
version: "3.0"
rules:
- rule: common_teenus_ilm_olemas
  condition:
  - slot_was_set:
    - common_teenus_ilm_asukoht: tallinn
  steps:
  - action: utter_common_teenus_ilm
  - action: action_restart
```

or https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml#L71-L72

#### Search for required forms

Forms are defined by defining `action` or `active_loop`, for example, `rules.rule.steps.action` or `rules.rule.steps.active_loop` with value(s) having a suffix `_form`

For example

```yaml
version: "3.0"
rules:
- rule: Activate custom fallback form
  steps:
  - action: utter_not_confident
  - action: custom_fallback_form
  - active_loop: custom_fallback_form
``` 

or https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml#L87-L88

#### Search for required responses within rules

Responses are defined by defining `action`, for example, `rules.rule.steps.action` with value(s) having a prefix `utter_`

For example

```yaml
version: "3.0"
rules:
- rule: common_hüvasti_jätmine
  steps:
  - intent: common_hüvasti_jätmine
  - action: utter_common_hüvasti_jätmine
``` 

or https://github.com/buerokratt/Training-Module/blob/main/mock1/data/rules.yml#L11
